# k8s/03-minio.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: worknest
spec:
  type: NodePort    # Changed from ClusterIP to NodePort
  selector:
    app: minio
  ports:
    - name: minio-api
      port: 9000
      targetPort: 9000
      nodePort: 30900  # Fixed external port for MinIO API
    - name: minio-console
      port: 9001
      targetPort: 9001
      nodePort: 30901  # Fixed external port for MinIO Console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: worknest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args: ["server", "/data", "--console-address", ":9001"]
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              value: "rootroot"
            - name: MINIO_ROOT_PASSWORD
              value: "rootroot"
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          emptyDir: {}


