# k8s/07-storage-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: storage-service
  namespace: worknest
spec:
  type: ClusterIP
  selector:
    app: storage-service
  ports:
    - name: http
      port: 5002
      targetPort: 5002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
  namespace: worknest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-service
  template:
    metadata:
      labels:
        app: storage-service
    spec:
      containers:
        - name: storage-service
          image: skitou/storage-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5002"
            - name: MINIO_INTERNAL_ENDPOINT
              value: "http://minio:9000"       # internal access
            - name: MINIO_ACCESS_KEY
              value: "rootroot"
            - name: MINIO_SECRET_KEY
              value: "rootroot"
            - name: MINIO_BUCKET
              value: "worknest-bucket"
            # Update this to use the NodePort (external) URL for MinIO API
            - name: MINIO_PUBLIC_URL
              value: "http://192.168.49.2:30900"  # Replace with your Minikube IP and NodePort
            - name: IDENTITY_SERVICE_URL
              value: "http://identity-service:5000"
            - name: FRONTEND_URL
              value: "http://localhost:4200"


